{
    "version": 1.0,
    "input_error": "\u001b[91mFout:\u001b[0m Ik weet niet zeker wat je hier mee bedoelt!",
    "back_to_menu": "Druk op [ENTER] om terug te keren naar het hoofdmenu",
    "cancel": "Annuleer",
    "intro_1": "Welkom in \u001b[1mPyPlace\u001b[0m!",
    "intro_2": "PyPlace is een Python applicatie die er voor zorgt \ndat je een simpel overzicht hebt van je andere Python \napplicaties, en het zorgt er ook voor dat je \ngemakkelijk nieuwe kunt installeren!",
    "replit_warning": "\u001b[93mWAARSCHUWING:\u001b[0m Het lijkt er op dat je dit uitvoert via de Replit pagina! Sommige dingen werken misschien niet correct dankzij verschillende namen van de bestanden. We raden aan om PyPlace te downloaden en het zelf uit te voeren.",
    "file_name_warning": "\u001b[93mWAARSCHUWING:\u001b[0m Het lijkt er op dat je dit uitvoert via een bestand dat niet \"pyplace.py\" heet. \nDit betekent dat je niet correct PyPlace kan updaten en herstellen. We raden je aan om het te veranderen naar \"pyplace.py\".",
    "setup_1": "Welk commando gebruik je om een Python bestand uit te voeren in je terminal?",
    "setup_2": "Laat het blank om te zetten naar de standaard. (python3)",
    "setup_3": "\u001b[1mLET OP:\u001b[0m Je kan dit later veranderen in de instellingen.",
    "setup_4": "\u001b[94mPyPlace instellen...\u001b[0m",
    "setup_5": "\u001b[92mPyPlace is ingesteld!\u001b[0m",
    "setup_6": "Druk op [ENTER] om PyPlace te starten",
    "main_menu_option_1": "Open een PyPlace app",
    "main_menu_option_2": "Voeg een PyPlace app toe",
    "main_menu_option_5": "Zoek naar app updates",
    "main_menu_option_3": "Open instellingen",
    "main_menu_option_4": "Verlaat PyPlace",
    "main_menu_message_1": "Wat wil je doen?",
    "main_menu_message_2": "Voer het nummer of de letter in voor wat je wilt doen:",
    "update_error_1": "\u001b[91mFout:\u001b[0m Kon niet zoeken naar updates! Antwoord code: [code]",
    "update_error_2": "\u001b[91mFout:\u001b[0m Kon het PyPlace bestand niet ophalen! Fout code: [code]",
    "update_warning_1": "\u001b[93mWAARSCHUWING:\u001b[0m Je huidige versie lijkt nieuwer te zijn dan de laatste versie die is gepubliceerd!",
    "update_message_1": "\u001b[1mUPDATE BESCHIKBAAR!\u001b[0m",
    "update_message_2": "Je huidige versie ([version]) is niet langer de nieuwste versie! De nieuwste versie is [version_latest].",
    "update_message_3": "Hier zijn de versie notities:",
    "update_message_4": "Wil je nu updaten?",
    "update_message_5": "\u001b[94mNieuwste versie van PyPlace downloaden...\u001b[0m",
    "update_message_6": "\u001b[92mDe nieuwste versie van PyPlace is nu beschikbaar in \u001b[1mPyPlace.py\u001b[0m\u001b[92m!\u001b[0m",
    "update_message_7": "Wil je het nu uitvoeren?",
    "update_message_8": "\u001b[94mProberen PyPlace.py uit te voeren...\u001b[0m",
    "update_message_9": "Verder gaan met huidige versie. \u001b[1mLET OP:\u001b[0m Volgende keer dat je PyPlace.py start, zal het op de nieuwste versie zijn!",
    "execute_file_error_1": "\u001b[91mFout:\u001b[0m Je hebt geen apps ge\u00efnstalleerd! Je kan ze toevoegen via \"Voeg een PyPlace app toe\" in het hoofdmenu.",
    "execute_file_error_2": "\u001b[91mFout:\u001b[0m Dit is geen Python bestand, dus kan het niet worden uitgevoerd door PyPlace.",
    "execute_file_message_1": "\u001b[93m\u25a0\u001b[0m: Experimentele applicatie",
    "execute_file_message_2": "\u001b[96m\u25a0\u001b[0m: Applicatie gedownload van de PyPlace Store",
    "execute_file_message_3": "Welk nummer app wil je openen?",
    "execute_file_message_4": "\u001b[94mProberen [app] te openen...\u001b[0m",
    "execute_file_message_5": "\u001b[92mBestand uitgevoerd!\u001b[0m",
    "download_file_error_1": "\u001b[91mFout:\u001b[0m Dit is geen Python bestand, dus kan het niet gedownload worden door Pyplace",
    "download_file_error_2": "\u001b[91mFout:\u001b[0m Kon het Python bestand niet downloaden! Status code [code]",
    "download_file_error_3": "\u001b[91mFout:\u001b[0m Een bestand met die naam ([name]) bestaat al!",
    "download_file_error_4": "\u001b[91mFout:\u001b[0m Dat lijkt niet een geldige URL te zijn!",
    "download_file_option_1": "URL naar Python bestand",
    "download_file_option_2": "Download van PyPlace Store",
    "download_file_option_3": "Download experiment",
    "download_file_option_4": "Voeg lokaal bestand toe",
    "download_file_message_1": "Hoe wil je een PyPlace app toevoegen?",
    "download_file_message_2": "Voer de directe URL naar het Python bestand in:",
    "download_file_message_3": "\u001b[94mPython app downloaden...\u001b[0m",
    "download_file_message_4": "\u001b[92mPython app gedownload!\u001b[0m",
    "download_file_message_5": "Hoe wil je dit bestand noemen?",
    "download_file_message_6": "Hoe wil je deze app noemen?",
    "download_file_message_7": "\u001b[94mPython app installeren...\u001b[0m",
    "download_file_message_8": "\u001b[92mPython app ge\u00efnstalleerd!\u001b[0m",
    "download_file_message_9": "Het kan nu geopend worden via \"Open een PyPlace app\" in het hoofdmenu!",
    "download_file_message_10": "Welk nummer app wil je downloaden?",
    "download_file_message_11": "Wat is de naam van het bestand dat je graag wilt toevoegen? \u001b[1mLet op:\u001b[0m Dit \u001b[4mMOET\u001b[0m in de huidige folder zijn.",
    "download_file_message_12": "Weet je zeker dat je een extern bestand wilt downloaden?",
    "settings_error_1": "\u001b[91mFout:\u001b[0m Dit is niet beschikbaar wanneer PyPlace wordt uitgevoerd in Replit. \u001b[1mJe kan in plaats daarvan PyPlace downloaden.\u001b[0m",
    "settings_option_1": "Verwijder een app",
    "settings_option_2": "Verander Python commando",
    "settings_option_3": "Herstel naar nieuwste versie",
    "settings_option_4": "Over",
    "settings_option_5": "Terug naar het hoofdmenu",
    "settings_option_6": "Beheer updater instellingen",
    "settings_message_1": "Vul het nummer of de letter voor wat je graag wilt doen:",
    "settings_message_2": "Welke apps wil je verwijderen? (gescheiden door een spatie, dus voor apps 1, 2 en 3, zou je 1 2 3 schrijven.)",
    "settings_message_3": "Wat wil je dat het nieuwe commando wordt? Laat leeg om het naar de standaard te zetten (python3).",
    "settings_message_4": "Commando ge\u00fcpdate naar [command]!",
    "settings_message_5": "Weet je zeker dat je wilt herstellen naar de nieuwste versie gepubliceerd online?",
    "settings_message_6": "\u001b[94mNieuwste versie van PyPlace downloaden...\u001b[0m",
    "settings_message_7": "\u001b[92mDe nieuwste versie van PyPlace is nu beschikbaar in \u001b[1mPyPlace.py\u001b[0m\u001b[92m!\u001b[0m",
    "settings_message_8": "Wil je het uitvoeren?",
    "settings_message_9": "\u001b[94mPyPlace.py proberen uit te voeren...\u001b[0m",
    "settings_message_10": "Verder gaan met huidige versie. \u001b[1mLET OP:\u001b[0m Volgende keer dat je PyPlace.py opstart, zal het de nieuwste versie zijn!",
    "settings_updater_option_1_a": "Zet zoeken naar updates aan",
    "settings_updater_option_1_b": "Zet zoeken naar updates uit",
    "settings_updater_option_2": "Zoek nu naar updates",
    "settings_updater_message_1_a": "\u001b[92mUpdater aangezet!\u001b[0m",
    "settings_updater_message_1_b": "\u001b[92mUpdater uitgezet!\u001b[0m",
    "settings_updater_message_2": "\u001b[92mGezocht naar updates!\u001b[0m",
    "bulk_delete_message_1": "\u001b[94mGeen apps om te verwijderen.\u001b[0m",
    "bulk_delete_message_2": "\u001b[92m[amount] app(s) verwijderd!\u001b[0m",
    "app_updater_error_1": "\u001b[91mFout:\u001b[0m Geen apps die je hebt ge\u00efnstalleerd via de PyPlace Store ondersetunen dit system (op dit moment)",
    "app_updater_message_1": "Wil je kijken of er een nieuwere versie is die het misschien ondersteund?",
    "app_updater_message_2": "Geen apps gevonden. Kijk later opnieuw.",
    "app_updater_message_4": "Alle apps zijn op de nieuwste versie!"
}
